"""creacion de tabla libros categorias

Revision ID: 8ab27684828c
Revises: 1a9efa2c4ab9
Create Date: 2026-09-23 22:41:21.186990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab27684828c'
down_revision = '1a9efa2c4ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libros_categorias',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'categoria_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libros_categorias')
    # ### end Alembic commands ###
