"""agregue la columna eliminado en libros

Revision ID: a18cfa188cb8
Revises: d9cf19d09559
Create Date: 2026-09-30 19:18:24.315363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18cfa188cb8'
down_revision = 'd9cf19d09559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    # ### end Alembic commands ###
