"""creacion de tabla libros escritores

Revision ID: d7c4560a527b
Revises: 8ab27684828c
Create Date: 2026-09-23 22:56:26.104553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c4560a527b'
down_revision = '8ab27684828c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libros_escritores',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('escritor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escritor_id'], ['escritores.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'escritor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libros_escritores')
    # ### end Alembic commands ###
